spring.application.name=VKtask

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vktask}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vktask}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vktask}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.sql.init.mode=never
